[#7] 유저 API 문서화
prgrms-web-devcourse/Team-Tasty-Masiottae-BE pull request #21
Opened 2022-07-28 07:28 UTC by chlwlgns524

## 개요
- 프론트엔드에서 API 기능 명세서 요청으로 인해 먼저 컨트롤러 테스트를 수행한 후 문서화를 하였습니다. 레포지토리와 서비스는 간단하게만 만들었고 차후에 수정할 예정입니다.

2022-07-29 09:21 UTC, haemin-jeong commented on src/main/generated/com/tasty/masiottae/account/domain/QAccount.java
> +public class QAccount extends EntityPathBase<Account> {
지훈님! 보통 깃에 Querydsl이 생성해주는 Qxxx 클래스들은 포함시키지 않는걸로 알고 있는데 확인 부탁드릴게요!

2022-07-29 09:28 UTC, haemin-jeong commented on src/main/java/com/tasty/masiottae/account/service/AccountService.java
> +@Getter
실수로 넣으신걸까요 지훈님?!🤔

2022-07-29 09:44 UTC, haemin-jeong requested changes
코멘트 확인 부탁드릴게요 지훈님🙇🏻‍♂️

2022-07-30 10:50 UTC, choi1204 commented
7번 브랜치 내용이 2번 브랜치 pr하면서 적용되어서 닫도록 하겠습니다.

2022-07-30 10:50 UTC, closed without merging